---
title: "Titanic"
author: "Tyler Jaszkowiak"
date: "April 25, 2018"
output: pdf_document
---


```{r load}
library(readr)
set.seed(123)
setwd("C:/Users/Tyler/Documents/kaggle/titanic")
origdata <- read_csv("train.csv", col_types = cols(
    Embarked = col_factor(levels = c("S", "C", "Q")),
    Sex = col_factor(levels = c("male", "female")),
    Survived = col_logical()))
unlist(lapply(lapply(origdata, is.na), sum))
dataset <- subset(origdata, select=c("Survived","Pclass","Sex","Age","SibSp","Parch","Fare"))
# include numeric transformations of other columns? (TODO more)
dataset$CabinNA <- is.na(origdata$Cabin)
dataset$MissInName <- grepl("Miss.", origdata$Name)
dataset$MrsInName <- grepl("Mrs.", origdata$Name)
dataset$isChild <- dataset$Age < 16


# TODO if we remove age == NA in training: how do we deal in testing? in final submission?
unlist(lapply(lapply(origdata, is.na), sum))
dataset <- dataset[!is.na(dataset$Age),] # TODO ?
#dataset$Age[is.na(dataset$Age)] <- mean(dataset$Age,na.rm=T) # TODO ?
```

```{r partition}
training.size <- floor(0.8*nrow(dataset))
sample.rows <- sample(nrow(dataset), training.size)
training <- dataset[sample.rows,]
testing <- dataset[-sample.rows,]
```


```{r explore}
summary(training)
par(mfrow=c(1,2))
hist(training$Age)
qqnorm(training$Age)
qqline(training$Age, col="red")
# fit a Gamma distribution to Age?
# TODO different distr? maybe a mixture of two gammas?
library("MASS")
fit <- fitdistr(training$Age,"gamma") # TODO why are NaNs produced?
x <- seq(0,80,length=800)
hist(training$Age,breaks=32)
lines(x, length(training$Age)*dgamma(x, fit$estimate["shape"], rate=fit$estimate["rate"]), col=2, lty=2)
```

```{r survivalVsAge}
# view relationship between age and survival
ageBlock <- c()
ageBlockSize <- c()
ageBlockSurvival <- c()
windowSize <- 4
nWindows <- 21
for (i in 1:nWindows)
{
  subset <- dataset$Survived[(i-1)*windowSize<=dataset$Age & dataset$Age<i*windowSize]
  ageBlock <- c(ageBlock, sprintf("[%i, %i)",(i-1)*windowSize,i*windowSize))
  ageBlockSize <- c(ageBlockSize, length(subset))
  ageBlockSurvival <- c(ageBlockSurvival, mean(subset))
}
cbind(ageBlock, ageBlockSize, ageBlockSurvival)
plot(1:nWindows*windowSize,ageBlockSurvival)
```


```{r explore-relationships}
numeric.cols <- unlist(lapply(training, is.numeric))
cor(training[,numeric.cols])
pairs(training[,numeric.cols])
```

TODO "Survived ~." -- see if interactions help
```{r regress}
regression <- as.formula("Survived ~ .")
lf <- glm(regression, family=binomial(link='logit'), data=training)
summary(lf)
plot(lf)
plot(lf$fitted.values[lf$y==0])
points(lf$fitted.values[lf$y==1],col=2,pch=2)
```

```{r crossval}
nFolds <- 10
folds_i <- sample(rep(1:nFolds, length.out=nrow(training)))
errors <- c()
for (k in 1:nFolds)
{
  # draw sample
  test_i <- which(folds_i == k)
  cvTrain <- training[-test_i,]
  validation <- training[test_i,]

  # fit the model
  lf <- glm(regression, family=binomial(link='logit'), data=cvTrain)
  fitted.results <- predict(lf,newdata=validation[,-1],type='response')
  fitted.results <- ifelse(fitted.results > 0.5,1,0)
  error <- mean(fitted.results != validation$Survived)
  # TODO get both type 1 and type 2 error
  errors <- append(errors, error)
}

print(paste('10F CV Accuracy: ',1-mean(errors)))
boxplot(errors)
```
